#!/bin/sh
commit_message=$(head -n 1 "$1")

if ! echo "$commit_message" | grep -Eq '^(Feat|Fix|Docs|Style|Refactor|Test|Chore|Design|Comment|Rename|Remove|!BREAKING CHANGE|!HOTFIX) : .+$'; then
    echo "Error: Commit message does not follow the convention!"
    exit 1
fi